---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mats
  template:
    metadata:
      labels:
        app: mats
    spec:
      containers:
        - name: mats
          image: <your-image-name>:<tag>
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mats-service
spec:
  selector:
    app: mats
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
